default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: koome
  password: koome
  host: localhost

development:
  <<: *default
  database: vehicle_miles_development

test:
  <<: *default
  database: vehicle_miles_test

production:
  <<: *default
  database: vehicle_miles_production
  username: koome
  password: <%= ENV['YOUR_PRODUCTION_DATABASE_PASSWORD'] %>
